version: '3'

services:
  database:
    container_name: mysql-rating
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
    - "1005:3306"
    environment:
      - MYSQL_DATABASE=ds
      - MYSQL_USER=kavi
      - MYSQL_ROOT_PASSWORD=iit123
      - MYSQL_PASSWORD=iit123

    volumes:
    - ./database/dbdt:/var/lib/mysql
    - ./database/initdb:/docker-entrypoint-initdb.d/:ro
  rating:
    container_name: ds-rating-v1
    build: ./ratings
    restart: always
    depends_on:
      - database
  communication:
    container_name: ds-communication-v1
    build: ./communication
    restart: always
    expose:
      - 9000
    ports:
    - 9000:9000
  ride-sharing:
    container_name: ds-ride_sharing-v1
    build: ./ride_sharing
    depends_on:
      - communication
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
    - 8005:80
    depends_on:
      - ride-sharing
      - rating